### PR TITLE
Core.Process: only set StandardEncoding if output/err is redirected

### PR DESCRIPTION
**Pull request by knocte**
### Description

Should potentially fix https://github.com/fsprojects/FAKE/issues/2670

### CODE REVIEW

**Comment by knocte** [comment]
@yazeedobaid I guess it was you who whitelisted me so that CI could run in this PR? I believe the macOS lane is not broken by my PR but because of a different issue which I filed here: https://github.com/fsprojects/FAKE/issues/2671

**Comment by yazeedobaid** [comment]
@knocte yes I approved the CI run. For first-time contributors, the CI needs admin approval.
Yes, it is not from your PR. It started to happen randomly after the last PR merge. It is happening on macOS only.

**Comment by yazeedobaid** [comment]
Hi thanks for the PR
Could you please rebase your branch from `release/next`? Now that the build has been fixed.

**Comment by knocte** [comment]
> Could you please rebase your branch from release/next?

Done.

**Comment by yazeedobaid** [comment]
Thanks for the fix, can u please try to add tests to it?

**Pull request merged**
