### PR TITLE
Update Paket.Core to support .NET 8.0

### PR DESCRIPTION
**Pull request by Thorium**
### Description

Updated Paket reference.

- fixes new instance of #2708

### CODE REVIEW

**Review by xperiandri — APPROVED** [review]

**Comment by xperiandri** [comment]
Do we need to mention this in the release notes? I suppose it does not affect anyone except maintainers and contributors

**Comment by Thorium** [comment]
This does affect if you run Paket restore via Fake. But I'd bundle with it under general .NET8 compatibility updates.

**Comment by xperiandri** [comment]
@Numpsy what do you think?

**Comment by Numpsy** [comment]
There are quite a few ```Could not detect any platforms from 'net8.0' in %package%``` warnings in the CI builds and it'd be nice to get that fixed, but i'm not using Paket myself so I don't know if there are any other ramifications of changing it

**Comment by Numpsy** [comment]
I see that Paket 8 also added support for .NET Framework 4.8.1, so maybe this change would be helpful to anyone using that as well?

**Comment by NogginBops** [comment]
This is blocking us from upgrading to `.net8.0`.
Would it be possible to release a prerelease version of FAKE with these fixes as a temporary measure?

**Comment by xperiandri** [comment]
Let me get back home next Monday and I will figure out how to release

**Comment by NogginBops** [comment]
@xperiandri Just a reminder about this, just in case. :slightly_smiling_face:

**Comment by NogginBops** [comment]
@xperiandri if there is anything I can help with that could speed up the release of the pre-release package I would be willing to give it a try. Also should I open a separate issue for this?

**Pull request merged**
