### PR TITLE
Update the Nuget.* package versions

### PR DESCRIPTION
**Pull request by Numpsy**
### Description

Updates references to Nuget.Protocol and related libraries to version 6.7.0, to avoid versions with known security vulnerabilities.

refs #2760 

## TODO

- I don't know if this should be updated to the current version (6.7.0) or the most-minimal update that is listed without vulnerabilities (6.0.5)?
- I know pretty much nothing about Paket, so I hope this is the right way to do an update
- It's possible that it'll conflict with the other pending PRs to update dependencies

### CODE REVIEW

**Comment by xperiandri** [comment]
Are only `packet.lock` changes required? Not `paket.dependencies` also?

**Comment by Numpsy** [comment]
It didn't update anything else when I did the update, but I do just notice that I updated the fakemodule group and not the fakerunner group, and I suppose those should be in step

**Comment by xperiandri** [comment]
Please, try updating one more time on top of the latest master from scratch

**Comment by Numpsy** [comment]
I tried updating and got merge conflcts, so instead of trying to update here I made a clean PR at #2764 2764

**Pull request closed without merging**
