### PR TITLE
Update version of Paket

### LINKED ISSUE #2708: Update Paket.Core to support .NET 7
### Description

Today Fake uses Paket.Core 6.2.1 that doesn't support .NET 7. There already exists a stable package of Paket.Core 7.1.5 that works fine with .NET 7.

### Repro steps

If you have paket.lock file that was created for .NET 7 running dotnet fake build can fail with error:
```
here was a problem while setting up the environment:
-> Error during parsing of 'C:\Users\mk185147\source\repos\ncr-swt-cfr\site-trust\paket.lock'.
-> invalid parameter 'net7.0' after >= or < in '== net7.0'
```

### PR DESCRIPTION
**Pull request by mk185147**
### Description

Current version of Fake contains Paket that isn't able to work with .NET 7 or nuget assemblies that talk about .NET 7 in dependency. I have updated Paket.Core to latest stable version which resulted in updating a few more packages which required small chagnes to code.

- fixes #2708

### CODE REVIEW

**Comment by yazeedobaid** [comment]
Thanks a lot! 🚀 🚀

**Comment by BlythMeister** [comment]
@yazeedobaid is there any chance of getting this into the fake 5.x versions?
as 6.x isn't released yet this is causing issues on a paket update

**Comment by yazeedobaid** [comment]
@BlythMeister sure I can release a version for FAKE 5, can anyone send a PR to the 5.x branch?
Also, is there anything preventing you from using FAKE v6 apart from not being released yet?

**Comment by BlythMeister** [comment]
I haven't tried as it's not released and as a company we actively avoid pre-release dependencies.

**Comment by BlythMeister** [comment]
@yazeedobaid i tried to do a PR to update paket.  but getting issues with it building.
noticed some other updates have been made for the net7 release, but i just can't get fake5 to build at all anymore!

even if i make a trivial change to the branch, the CI won't actually build it

**Comment by yazeedobaid** [comment]
@BlythMeister Thanks for sending a PR. I didn't look into the complete details, but it seems issues are caused by dependencies resolutions by FAKE runner. Not sure if it is related to it, but we had also to drop support for NETSTANDARD 2.0 in the FAKE runner for it to work with updated dependencies.

The pre-releases of v6 are out by now for almost 3 months. I think we can publish the first stable release of it. Does this work for you? I can plan for a release early next week.

**Comment by BlythMeister** [comment]
Yeah, I can wait for that 🙂

**Comment by yazeedobaid** [comment]
@BlythMeister I have published the 6.0.0 version.

**Pull request merged**
