### PR TITLE
add Context.setExecutionContextFromCommandLineArgs

### PR DESCRIPTION
**Pull request by cataggar**
This moves this [boilerplate](https://github.com/fsprojects/FAKE/issues/2719#issuecomment-1470687052) into a function. A minimal build script that works on .NET 6 & .NET 7 with Visual Studio IntelliSense and works with private NuGet feeds will now be:

``` fsi
#!/usr/bin/env -S dotnet fsi
#r "nuget: Fake.Core.Target"

Fake.Core.Context.setExecutionContextFromCommandLineArgs __SOURCE_FILE__

open Fake.Core

Target.create "clean" (fun _ ->
  Trace.log "Cleaning stuff"
)

Target.create "build" (fun _ ->
  Trace.log "Building the app"
)

Target.create "deploy" (fun _ ->
  Trace.log "Deploying app"
)

open Fake.Core.TargetOperators

"clean"
  ==> "build"
  ==> "deploy"

Target.runOrList()
```

This can be run with `dotnet fsi build.fsx`. On Linux or Mac OSX, this can be run with `./buid.fsx` as well.

### CODE REVIEW

**Review by xperiandri — DISMISSED** [review]

**Comment by xperiandri** [comment]
What if executed not from the script?

**Comment by xperiandri** [comment]
Maybe it must be in the separate package?

**Comment by xperiandri** [comment]
Will we add the line about this to the release notes?
https://github.com/fsprojects/FAKE/pull/2778/files

**Comment by Numpsy** [comment]
Looks like the build failures for this one are because Fantomas wants the code to be formatted

**Comment by xperiandri** [comment]
Completed in #2785

**Pull request closed without merging**
