### PR TITLE
On Unix like OSs, look for sqlpackage in directories specified in $PATH

### PR DESCRIPTION
**Pull request by nickgravgaard**
This PR addresses issue https://github.com/fsprojects/FAKE/issues/2701 of sqlpackage not existing in the same place on MacOS and Linux distros by following the canonical Unix practice of searching the directories specified by the `PATH` environment variable instead of using a hard-coded path.

### CODE REVIEW

**Comment by mattgallagher92** [comment]
I've tested this out in my Ubuntu environment, where I have a symlink in `/usr/local/bin` to my `sqlpackage` install location, by running the expression Nick has added in F# interactive. It resolves correctly:

```fsharp
    Environment.pathDirectories
    |> Seq.map (fun dir -> !!(dir </> "sqlpackage"))
    |> Seq.concat
    |> Seq.map (fun path -> path, 15)

val it: seq<string * int> = seq [("/usr/local/bin/sqlpackage", 15)]
```

**Comment by yazeedobaid** [comment]
Thanks for the PR,
I would like to suggest keeping both ways. The old hard-coded way and the commonplace (best practice) as you mentioned. From what I see, now it will search in environment variables only. I'm thinking about a case when a user doesn't have SQL Package in the environment variables but is added to the directory that was hard-coded.

**Comment by yazeedobaid** [comment]
@mattgallagher92 thanks for testing and confirming the fix

**Comment by nickgravgaard** [comment]
Thanks @yazeedobaid, that sounds reasonable - I've just pushed up a new commit. First it checks `$PATH` as that's where users can define their own locations for binaries, falling back to `/usr/local/bin` (normal user binaries not managed by the distro's package manager, eg. locally compiled packages), and finally `/usr/bin` (distro-managed normal user binaries).

**Pull request merged**
