### PR TITLE
SdkAssemblyResolver: Use dotnet --version to resolve the correct SDK

### LINKED ISSUE #2641: SdkAssemblyResolver does not properly resolve locally installed runtime
### Description

After upgrading to 5.21.0, our .NET 6 builds are failing due to the following error:

```
System.ArgumentException: The option value was None (Parameter 'option')
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 11
   at Fake.Runtime.SdkAssemblyResolver.SdkAssemblyResolver.ResolveSdkRuntimeVersion() in D:\a\FAKE\FAKE\src\app\Fake.Runtime\SdkAssemblyResolver.fs:line 89
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

This appears to be due to the resolver not being able to resolve the correct Runtime version for the locally installed SDK.  We are using `global.json` to specify an SDK version along with `rollForward` to help manage any minor SDK version differences between development machines and build agents.

### Repro steps

The following steps will reproduce the issue outside of the FAKE pipeline by calling the appropriate methods on the `SdkAssemblyResolver` class:

#### Setup: In an empty folder create `Resolver.fsx` with the following code:
```
#r "nuget: Fake.DotNet.Cli"
#r "nuget: Fake.Runtime"

open Fake.DotNet
open Fake.Runtime

let resolver = SdkAssemblyResolver.SdkAssemblyResolver(Trace.Verbose)
resolver.ResolveSdkRuntimeVersion() |> printfn "%s"
```

Note the currently installed .NET SDK(s) on your machine.  The expected behavior as written assumes `6.0.101`, but this is also reproduceable with `6.0.100`

## Scenario 1: No global.json
1. run `dotnet fsi Resolver.fsx`

### Expected behavior
```
Trying to resolve runtime version from network..
resolved runtime version: 6.0.1
6.0.1
```

### Actual behavior
```
System.ArgumentException: The option value was None (Parameter 'option')
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 11
   at Fake.Runtime.SdkAssemblyResolver.SdkAssemblyResolver.ResolveSdkRuntimeVersion() in D:\a\FAKE\FAKE\src\app\Fake.Runtime\SdkAssemblyResolver.fs:line 89
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

## Scenario 2: Unknown SDK version with rollForward option
1. Add the following `global.json` to the workspace
```
{
  "sdk": {
    "version": "6.0.0",
    "rollForward": "latestFeature"
  }
}
```

2. run `dotnet fsi Resolver.fsx`

### Expected behavior
```
Trying to resolve runtime version from network..
resolved runtime version: 6.0.1
6.0.1
```

### Actual behavior
```
System.ArgumentException: The option value was None (Parameter 'option')
   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 11
   at Fake.Runtime.SdkAssemblyResolver.SdkAssemblyResolver.ResolveSdkRuntimeVersion() in D:\a\FAKE\FAKE\src\app\Fake.Runtime\SdkAssemblyResolver.fs:line 89
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
```

## Scenario 3: Valid SDK version, lower than installed version
1. Add the following `global.json` to the workspace
```
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestFeature"
  }
}
```

2. run `dotnet fsi Resolver.fsx`

### Expected behavior
```
Trying to resolve runtime version from network..
resolved runtime version: 6.0.1
6.0.1
```

### Actual behavior
```
Trying to resolve runtime version from network..
resolved runtime version: 6.0.0
6.0.0
```

During the actual build this leads to a failure due to the fact that 6.0.0 is not installed:

```
The last restore is still up to date. Nothing left to do.
Performance:
 - Cli parsing: 126 milliseconds
 - Packages: 44 milliseconds
   - Creating Runtime Graph: 43 milliseconds
   - Retrieve Assembly List: 1 second
 - Runtime: 1 second
There was a problem while setting up the environment:
-> Could not find referenced assemblies in path: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0', please check installed SDK and runtime versions
Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.
```

### Known Workarounds
Specify exact installed SDK in `global.json` ensure that version is installed across all machines building the project 

### Related information 

FAKE 5.21.0

Installed SDKs:
```
dotnet sdk check
.NET SDKs:
Version      Status
---------------------------------------------------
2.2.207      .NET 2.2 is out of support.
3.1.416      Up to date.
5.0.104      .NET 5.0 is going out of support soon.
5.0.210      .NET 5.0 is going out of support soon.
5.0.404      .NET 5.0 is going out of support soon.
6.0.101      Up to date.

.NET Runtimes:
Name                              Version      Status
-------------------------------------------------------------------------------------
Microsoft.AspNetCore.All          2.2.8        .NET 2.2 is out of support.
Microsoft.AspNetCore.App          2.2.8        .NET 2.2 is out of support.
Microsoft.NETCore.App             2.2.8        .NET 2.2 is out of support.
Microsoft.AspNetCore.App          3.1.22       Up to date.
Microsoft.NETCore.App             3.1.22       Up to date.
Microsoft.WindowsDesktop.App      3.1.22       Up to date.
Microsoft.NETCore.App             5.0.0        .NET 5.0 is going out of support soon.
Microsoft.AspNetCore.App          5.0.4        .NET 5.0 is going out of support soon.
Microsoft.NETCore.App             5.0.4        .NET 5.0 is going out of support soon.
Microsoft.WindowsDesktop.App      5.0.4        .NET 5.0 is going out of support soon.
Microsoft.AspNetCore.App          5.0.13       .NET 5.0 is going out of support soon.
Microsoft.NETCore.App             5.0.13       .NET 5.0 is going out of support soon.
Microsoft.WindowsDesktop.App      5.0.13       .NET 5.0 is going out of support soon.
Microsoft.AspNetCore.App          6.0.1        Up to date.
Microsoft.NETCore.App             6.0.1        Up to date.
Microsoft.WindowsDesktop.App      6.0.1        Up to date.
```

OS: Win 10

### PR DESCRIPTION
**Pull request by mclark1129**
### Description

This PR updates the `SdkAssemblyResolver` to use `dotnet --info` in order to resolve the most appropriate runtime for a project.

If available, link to an existing issue this PR fixes. For example:

- fixes #2641 

## TODO

- Tests, but want to make sure the solution is acceptable first.

Feel free to open the PR and ask for help

- [ ] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [ ] unit or integration test exists (or short reasoning why it doesn't make sense)
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [ ] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [ ] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [ ] (if new module) the module is in the correct namespace
- [] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [ ] Fake 5 [API guideline](https://fake.build/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by cataggar** [comment]
Looks like this may fix #2648 as well.

**Comment by mclark1129** [comment]
@yazeedobaid Any idea when someone might be able to take a look at this PR?  I logged this issue over a month ago and a proposed fix over a week ago.  We have several projects using FAKE in my organization and #2641 is causing a fair amount of headaches with our build agents.

**Comment by yazeedobaid** [comment]
@mclark1129 Thanks for the PR and sorry for the later response.
As I understand this will make the `global.json` unnecessary and it will resolve the DotNet SDK from whatever the DotNet host is using. And this opens the possibilities to resolve any SDK version, for example, v5. And we don't want that since we have pinned the reference assemblies to Net6 since it is the LTS release.

Can you please confirm/add tests for cases in which if DotNet host is using for example v5 then what output will be?
I think we can provide a descriptive message that Fake runner works with Net6 SDK? Or do you have any other ideas?

Also, why not provide the two options? From a `global.json` and DotNet host?

**Comment by mclark1129** [comment]
@yazeedobaid No problem, just want to help out getting this issue resolved!

As far as I understand it, the current code would not allow an SDK other than 6 to resolve its runtime, due to https://github.com/fsprojects/FAKE/blob/202d04e5c0c463b5d46ec52f8d13fa98ee0c1be0/src/app/Fake.Runtime/SdkAssemblyResolver.fs#L62

Since this filters out only releases with a product version of `6.0`, the runtime assembly for an SDK other than 6 would fail to resolve.

> Also, why not provide the two options? From a global.json and DotNet host?

The issue is that trying to manually read from the global.json doesn't contain enough logic to properly resolve an appropriate local SDK.  By using `dotnet --version` we get to reuse the CLI's logic without having to re-implement it, and it also effectively provides both options.  The CLI can resolve from a global.json if present and if not will fall back to the most appropriate for the specified runtime.  

I'll confirm the output in the event only .NET 5 or lower is installed, and add test cases.  I'm also happy to clean up a bit more in that area (boyscout rule) to help ensure the appropriate error messages are returned with resolution fails.  I didn't want to come in with my first PR changing everything around without asking first :).

**Comment by yazeedobaid** [comment]
@mclark1129 Thanks a lot

**Comment by mclark1129** [comment]
@yazeedobaid I went ahead and removed the global.json check.  As far as I can tell, all tests are passing with the exception of the `Fake.DotNet.NuGet.Tests/Search by title returns results for matching packages by provided title`.  This one is also failing in https://github.com/fsprojects/FAKE/pull/2667 so I'm inclined to believe it's not a result of any of my changes.  Do I need to try and fix up that test as a part of my PR in order to move this one forward?

**Comment by yazeedobaid** [comment]
@mclark1129 if you could help in fixing that failing test that would be great. Thanks!

**Comment by mclark1129** [comment]
@yazeedobaid I fixed the failing NuGet test and then ran into another issue with `DotNet.uninstallTemplate`.  Looks like the code was incorrectly throwing an error if the template was not already installed, despite returning exit code 0.  I updated the check to first look if the exit code is 0, and if not then it can check to see if the messages indicate that the template was not found.  Not sure if that was a behavior change between SDK versions, but I'm not sure why the test couldn't find the message to begin with.

Anyways, `dotnet fake build` is returning 100% success locally, so hopefully the workflow should complete successfully the next time it runs.  No idea yet if we'll see any issues during the linux builds.  If you wouldn't mind triggering that as soon as you're able I would appreciate it.

**Comment by mclark1129** [comment]
@yazeedobaid TIL I learned how to run the checks from my forked repo! 🚀 There is at least one test still failing due to the fact that `dotnet --version` changed stdout slightly from what the test was expecting.  Doesn't seem to impact windows locally, so possibly some environmental difference on linux.  Once I get the checks passing on my fork I'll get you to run them again.  Thanks!

**Comment by mclark1129** [comment]
@yazeedobaid Ok I have a green run on my fork https://github.com/mclark1129/FAKE/pull/1/checks, would you mind re-running the workflow when you're available?

**Comment by yazeedobaid** [comment]
Thanks a lot for the PR.
I'll try to publish a release as soon as I can.

**Comment by mclark1129** [comment]
@yazeedobaid If you can cut a pre-release first I can pull it in and test it out on our builds.

**Comment by yazeedobaid** [comment]
@mclark1129 It seems the build is failing on macOS. Could you please check?

https://github.com/fsprojects/FAKE/pull/2668

**Pull request merged**
