### PR TITLE
Add ignoreConflicts parameter to paket push

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
### Description

Add missing parameter `ignoreConflicts` from `paket push`

## TODO

Feel free to open the PR and ask for help

- [x] New (API-)documentation for new features exist (Note: API-docs are enough, additional docs are in `help/markdown`)
- [x] unit or integration test exists (or short reasoning why it doesn't make sense)
  
  > Note: Consider using the `CreateProcess` API which can be tested more easily, see https://github.com/fsharp/FAKE/pull/2131/files#diff-4fb4a77e110fbbe8210205dfe022389b for an example (the changes in the `DotNet.Testing.NUnit` module)
  
- [x] boy scout rule: "leave the code behind in a better state than you found it" (fix warnings, obsolete members or code-style in the places you worked in)     
- [x] (if new module) the module has been linked from the "Modules" menu, edit `help/templates/template.cshtml`, linking to the API-reference is fine.
- [x] (if new module) the module is in the correct namespace
- [x] (if new module) the module is added to Fake.sln (`dotnet sln Fake.sln add src/app/Fake.*/Fake.*.fsproj`)
- [x] Fake [API guideline](https://fake.build/guide/contributing.html#API-Design-Guidelines) is honored

### CODE REVIEW

**Comment by yazeedobaid** [comment]
Thanks for contributing. Could you please rebase your branch from master? We have fixed the failing build.
Also, could you please provide a description of the PR?

**Comment by gdziadkiewicz** [comment]
Yes, will do that
________________________________

**Comment by gdziadkiewicz** [comment]
Refreshed the branch with master and added a description. I will do some more testing and provide the test results here before progressing from draft.

**Comment by yazeedobaid** [comment]
Thanks! Released in `6.0.0-beta001`

**Pull request merged**
