### PR TITLE
Fix dotnet fsi call

### PR DESCRIPTION
**Pull request by pchinery**
### Description

The call to `dotnet fsi` had a typo

### CODE REVIEW

**Comment by voronoipotato** [comment]
@matthid  this is a simple docs typo, can we get a merge :) Thank you!!

**Comment by xperiandri** [comment]
Anybody here?

**Comment by xperiandri** [comment]
Fixed in the earlier PR, but thanks anyway

**Comment by pchinery** [comment]
> Fixed in the earlier PR, but thanks anyway

@xperiandri What do you mean with fixed? The typo still is live: https://fake.build/guide/getting-started.html

**Comment by xperiandri** [comment]
Docs were not deployed

**Comment by xperiandri** [comment]
But the fix is in the repo in the main branch

**Pull request closed without merging**
