### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by Numpsy**
refs https://github.com/fsprojects/FAKE/issues/2738#issuecomment-2146284145

This is just grabbing a couple of notable changes, and I'm not sure what the next version will be, so maybe it's a placeholder than a complete change

### CODE REVIEW

**Comment by Numpsy** [comment]
Also, the macOS CI builds might fail unless we do https://github.com/fsprojects/FAKE/pull/2773 or similar

**Comment by voronoipotato** [comment]
Looks great! Thanks @Numpsy !! 🎉🎉🎉

**Review by voronoipotato — APPROVED** [review]

**Review by xperiandri — APPROVED** [review]

**Comment by xperiandri** [comment]
Does anyone know how to fix the build?

**Comment by Numpsy** [comment]
> Does anyone know how to fix the build?

If the issue is https://github.com/dotnet/runtime/issues/64103 then it looks like either change the macOS runner from macOS-latest to macOS(12/13) (e.g. #2773) or update the .NET SDK used in the build to 6.0.300 or newer.

**Comment by smoothdeveloper** [comment]
@xperiandri I noticed in #2768 (which also updates release notes) that you rebased / repushed commits I did in that branch, I think it is better to just append commits and let the branch author do rebase in case it is needed, there is also concern it can mess the contribution history in github (which is nice for people that begin contribution).

#2768 should be merged and released, IMO, it is not because macOS CI fails in that particular branch, that it is related to it, most FAKE users can't leverage terminal logger goodness until it ships.

**Comment by xperiandri** [comment]
@smoothdeveloper let's fix the build in a separate PR and rebase this one on top. Anyway, if a build does not happen I will not be able to release anything. A release also requires building 🙂

**Comment by voronoipotato** [comment]
@xperiandri how do we update .net core to 6.0.5 for that the macOS-latest target so we can keep moving?

**Comment by xperiandri** [comment]
Submit another PR with a fix

**Comment by Numpsy** [comment]
> @xperiandri how do we update .net core to 6.0.5 for that the macOS-latest target so we can keep moving?

I tried doing it in #2780 and got a different error :-(

**Comment by Numpsy** [comment]
Grasping at straws a bit here, but  - https://github.com/fsprojects/FAKE/pull/2781.
(Unclear if there is actually a real FAKE issue here on ARM cpu macs that might effect end users as well)

**Comment by voronoipotato** [comment]
@Numpsy  maybe we should reach out to people in the slack and discord and see if anyone has an arm macbook that they can help test this with. I have an arm surface pro x, but I doubt that will be helpful.

**Comment by Numpsy** [comment]
At this point, I think it might be nice to just try to get the build pipeline running successfully on the Intel Mac runners, and have 'fix ARM problems' as a seperate work item once there's a more stable base

**Comment by Numpsy** [comment]
Hurrah, build succeeded

**Pull request merged**
