### PR TITLE
Update MSBuild.StructuredLogger to handle newer versions

### PR DESCRIPTION
**Pull request by TheAngryByrd**
### Description

Closes https://github.com/fsharp/FAKE/issues/2595

With the latest version of dotnet sdk (5.0.300), running FAKE gets this error:

> Unsupported log file format. Latest supported version is 9, the log file has version 13.

This updates MSBuild.StructuredLogger to be able to handle it.  MSBuild.StructureLogger [added support in 2.1.397](https://github.com/KirillOsenkov/MSBuildStructuredLog/releases/tag/v2.1.397).

### CODE REVIEW

**Comment by ImaginaryDevelopment** [comment]
Is [this](https://github.com/fsharp/FAKE/issues/2595) workaround working for you? It isn't for me so far when trying to build in docker @TheAngryByrd

**Comment by TheAngryByrd** [comment]
> Is [this](https://github.com/fsharp/FAKE/issues/2595) workaround working for you? It isn't for me so far when trying to build in docker @TheAngryByrd

I haven’t tried but I’ll try them soon

**Comment by yazeedobaid** [comment]
> Is this workaround working for you? It isn't for me so far when trying to build in docker @TheAngryByrd

I tried the workaround in a project and it worked.

@TheAngryByrd could you please look into the Travis build? It seems one of the integration tests is failing.
I cloned the branch and run integration tests on my machine (Windows 10) and it passes. Maybe it is something with Linux!

**Comment by yazeedobaid** [comment]
Thanks for the contribution
Will close this because it is outdated and the structured logger version has been updated in the latest releases.
Please feel free to update the PR and open it again if the issue is still exists.

Thanks

**Pull request closed without merging**
